spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/compra
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: compra
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect




